### ISSUE TITLE
"print iris.load" shows some GRIB fields as "unknown"

### ISSUE THREAD

**Issue by captcha1** [SciTools/scitools.org.uk#98]
"print iris.load" shows some fields as "unknown"

For example, with this GRIB2 file : http://bv.waihee.org/gfs.2015010800/gfs.t00z.pgrbf0-96-3.2p5deg.grib2 , doing "print iris.load" shows one field as "unknown", but when I convert that file to NetCDF (using "wgrib2") : http://bv.waihee.org/gfs.2015010800/gfs.t00z.pgrbf0-96-3.2p5deg.nc ) and do "print iris.load" on it, then the field shows up as "Precipitation Rate / (kg/m^2/s)" .  I suspect this is because wgrib2 is reading "nameECMF" (or "name") field, whereas "iris.load" is reading "cfNameECMF" (or "cfName").

Another example : this GRIB1 file : http://bv.waihee.org/gfs.2015010800/gfs20150108081701674.grb .  Three fields show up as "unknown" . grib_dump shows them as "Mean sea level pressure", "Precipitation rate" and "Geopotential Height" (strangely, cfNameECMF = geopotential_height, so iris.load is apparently not using the "cfNameECMF" field).  FYI, I got this GRIB1 file from "http://saildocs.com", which is a GRIB email service used by sailors over slow data connections.

Thanks,
Ken

**Comment by esc24** [comment]
Hi @captcha1  - this issue really belongs in https://github.com/scitools/iris rather than here. However, I took a look and added the mapping from grib discipline 0, categoryNumber 1, parameterNumber 7 to precipitation flux to the metOcean project (https://github.com/metarelate/metOcean/pull/38), and created a subsequent Iris PR (https://github.com/SciTools/iris/pull/1523) to fix your first issue. If you have more mappings you'd like to contribute please look at https://github.com/metOcean.

**Comment by captcha1** [comment]
Oops, sorry for posting the wrong project.

Thanks very much for your quick response

Thanks,
Ken
